// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGfe3AO839u9-2Esm4xBu9_vR_guS5qHo',
    appId: '1:444753173579:web:2db658f708e93bafe181ce',
    messagingSenderId: '444753173579',
    projectId: 'suhii-ef849',
    authDomain: 'suhii-ef849.firebaseapp.com',
    storageBucket: 'suhii-ef849.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz8le2lsgfagp3HHZGPg0Q5E4w-6ADCCQ',
    appId: '1:444753173579:android:1370c3927b0698a6e181ce',
    messagingSenderId: '444753173579',
    projectId: 'suhii-ef849',
    storageBucket: 'suhii-ef849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz4vYzkNgbXqn3rC_nU6Hhwpc49dxZMH4',
    appId: '1:444753173579:ios:eff47ba10ea61217e181ce',
    messagingSenderId: '444753173579',
    projectId: 'suhii-ef849',
    storageBucket: 'suhii-ef849.firebasestorage.app',
    iosBundleId: 'com.example.nailSuhii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz4vYzkNgbXqn3rC_nU6Hhwpc49dxZMH4',
    appId: '1:444753173579:ios:eff47ba10ea61217e181ce',
    messagingSenderId: '444753173579',
    projectId: 'suhii-ef849',
    storageBucket: 'suhii-ef849.firebasestorage.app',
    iosBundleId: 'com.example.nailSuhii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGfe3AO839u9-2Esm4xBu9_vR_guS5qHo',
    appId: '1:444753173579:web:48c01b0741c73478e181ce',
    messagingSenderId: '444753173579',
    projectId: 'suhii-ef849',
    authDomain: 'suhii-ef849.firebaseapp.com',
    storageBucket: 'suhii-ef849.firebasestorage.app',
  );
}
